name: Train Model

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'   # Trigger only when files in data/ change
      - 'train/**'  # Trigger only when files in train/ change

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r train/requirements.txt

      - name: Run training script
        run: |
          python train/train.py
